title:        "East of the Sun, West of the Moon"
languageCode: "en-us"
theme:        "ananke"

copyright: "Erwin Harte"

# I enable this, but my actual environment is "live", not "production", so
# at the moment I reject all (search engine) bots, for whatever that's worth.
enableRobotsTXT: true

menu:
  main:
    - name: 'Posts'
      pageRef: '/post/'
      weight: 10
    - name: 'Projects'
      pageRef: '/project/'
      weight: 20
    - name: 'Contact'
      pageRef: '/contact'
      weight: 30
    - name: 'About'
      pageRef: '/about'
      weight: 40

markup:
  highlight:
    # lineNos: true
    # lineNumbersInTable: true
    # Doesn't seem to work?

params:
  author: "Erwin"
  recent_posts_number: 1
  show_reading_time: true
  ananke_socials:
    - name: "mastodon"
      url:  "https://strangeweb.page/@jochie"
      rel:  "me noopener"
    - name: "github"
      url:  "https://github.com/jochie"
      rel:  "me noopener"
    - name: "stackoverflow"
      url: "https://stackoverflow.com/users/19301214/"
    - name: "linkedin"
      url:  "https://www.linkedin.com/in/erwinharte/"
      rel: "me noopener"
      share: false
    - name: "rss"
      label: "RSS"
      url:  "/post/index.xml"

  mainSections: "nothing"

permalinks:
  post: '/post/:year/:month/:title/'

deployment:
  order: [".jpg$", ".jpeg$", ".gif$", ".png$"]
